apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: xtjdbkvhy-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/xtjdbkvhy-java-springboot-gitops